#!/bin/sh

# keybinds
pkill sxhkd
sxhkd &

# terminal daemon
pkill urxvtd
urxvtd --quiet --opendisplay --fork

# panels
pkill polybar
polybar top &
polybar bottom &
polybar secondary &

# cursor
xsetroot -cursor_name left_ptr

# music
pkill mpd
mpd &

# compositor
pkill compton
compton --config $XDG_CONFIG_HOME/compton/compton.conf &

bspc config border_width        1
bspc config window_gap          5

# Set monitor order
bspc wm -O DP-4 DVI-I-1

# Primary monitor
bspc monitor DP-4 -d term dev game chat I II III IV
# bspc monitor DP-4 -n 0 -d www term dev game I II III IV


# Secondary monitor
bspc monitor DVI-I-1 -d www steam 9 0
# bspc monitor DVI-I-1 -n 1 -d steam chat 9 0

# i=1
# for monitor in $(bspc query -M); do
# bspc monitor $monitor \
#         -n "$i" \
#         -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
#     let i++
# done
# NMON=$i
# unset i

bspc config top_padding 14

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

# bspc config normal_border_color "#332d29"
# bspc config active_border_color "#817267"
# bspc config focused_border_color "#504339"
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Firefox desktop=www follow=off

bspc rule -a Steam desktop=steam follow=off split_ratio=0.75

bspc rule -a discord desktop=chat follow=off split_ratio=0.65
bspc rule -a ts3client desktop=chat follow=off
bspc rule -a 'TeamSpeak 3' desktop=chat follow=off

bspc rule -a factorio desktop=game
bspc rule -a Screeps desktop=game
bspc rule -a FTL.amd64 desktop=game

# SS13 window fix
bspc rule -a dreamseeker.exe rectangle=300x150+960+540
